#!/usr/bin/env bash
### mkradmin-trigger -- trigger confirmed multisig action
### Usage: mkradmin trigger <action>
set -e
fail() { echo >&2 "${0##*/}: $*"; exit 1; }

action=$(mkradmin action "${1?which action?}")
get() { seth --field "$1" <<<"$action"; }

if [[ $(get expired) = true ]]; then
  fail "error: action $1 expired"
elif [[ $(get confirmed) = false ]]; then
  fail "error: action $1 not confirmed"
elif [[ $(get triggered) = true ]]; then
  fail "error: action $1 already triggered"
fi

echo "Triggering action $1..."
seth send @mkr_ms "trigger(uint)" "$1"

action=$(mkradmin action "$1")

if [[ $(get triggered) = true ]]; then
  echo "Action $1 successfully triggered."
else
  fail "failed to trigger action $1"
fi
