#!/usr/bin/env bash
### mkradmin-confirm -- confirm a proposed multisig action
### Usage: mkradmin confirm <action>
set -e
fail() { echo >&2 "${0##*/}: $*"; exit 1; }
echo "Confirming action ${1?which action?}..."

seth send @mkr_ms "confirm(uint)(bool)" "$1" ||
fail "error: failed to confirm action $1"

echo "Successfully confirmed action $1."
