#!/usr/bin/env bash
### mkradmin-action -- print information about a multisig action
set -e
action=${1?which action?}
sig="getActionStatus(uint256)(uint256,uint256,bool,address,uint256)"
values=($(seth call @mkr_ms "$sig" "$action"))

confirmations=$(seth --to-dec "${values[0]}")
expiration=$(seth --to-dec "${values[1]}")
triggered=${values[2]}
target=$(seth --to-address "${values[3]}")
value=$(seth --to-dec "${values[4]}")
value=$(seth --to-eth "$value")

if (($(date +%s) >= expiration)); then
  expired=true
else
  expired=false
fi

quorum=${MKRADMIN_QUORUM-$(mkradmin info | seth --field quorum)}
if ((confirmations >= quorum)); then
  confirmed=true
else
  confirmed=false
fi

if [[ $triggered = true ]]; then
  status=Triggered
elif [[ $expired = true ]]; then
  status=Expired
elif [[ $confirmed = true ]]; then
  status=Untriggered
else
  status=Unconfirmed
fi

if [[ $expiration = 0 ]]; then
  echo >&2 "${0##*/}: error: no such action: $1"
  exit 1
else
  properties=(
    confirmations
    confirmed
    expiration
    expired
    status
    target
    triggered
    value
  )
  for name in "${properties[@]}"; do  
    printf "%-15s\t%s\n" "$name" "${!name}"
  done
fi
