#!/usr/bin/env bash
### mkradmin -- MakerDAO admin multisig CLI
### Usage: mkradmin <command> [<args>]
###    or: mkradmin <command> --help

set -e

if [[ $2 = --help ]]; then
  exec mkradmin-help "$1"
elif [[ ${1-help} = help ]]; then
  exec mkradmin-"${1-help}" "${@:2}"
fi

if ! [[ $MKRADMIN_RUNNING ]]; then
  export MKRADMIN_RUNNING=1
  [[ -e ~/.mkradminrc ]] && . ~/.mkradminrc
  now=$(date +%s)
  last=$(seth block latest timestamp)
  age=$((now - last))
  if ((age > 600)); then
    echo >&2 "${0##*/}: warning: the last block is $age seconds old"
    echo >&2 "${0##*/}: ensure the chain is synced and the clock is accurate"
  fi
fi

ETH_FROM=@mkradmin_account mkradmin-"$@"
