#!/usr/bin/env bash
### mkradmin -- MakerDAO admin multisig CLI
### Usage: mkradmin <command> [<args>]
###    or: mkradmin <command> --help

set -e

if [[ $2 = --help ]]; then
  exec "${0##*/}" help "$1"
elif [[ ${1-help} = help ]]; then
  exec "${0##*/}-${1-help}" "${@:2}"
fi

if ! [[ $MKRADMIN_INITIALIZED ]]; then
  export MKRADMIN_INITIALIZED=1
  [[ -e ~/.mkradminrc ]] && . ~/.mkradminrc
  now=$(date +%s)
  last=$(seth block latest timestamp)
  age=$((now - last))
  if ((age > 600)); then
    echo >&2 "${0##*/}: warning: the last block is $age seconds old"
    echo >&2 "${0##*/}: ensure that chain is synced and clock is accurate"
  fi
fi

export SETH_FROM=${SETH_FROM-$MKRADMIN_ACCOUNT}
exec "${0##*/}-$@"
