#!/usr/bin/env bash
### mkradmin-propose -- propose a new multisig action
### Usage: mkradmin propose <target> <sig> [<args>]
###    or: mkradmin propose <target> <data>
###
### Submit a proposal for the multisig to call <target> with <data>.
### If <sig> has the form `<name>(<types>)', then infer <data> from <args>.
set -e
fail() { echo >&2 "${0##*/}: $*"; exit 1; }
[[ $2 ]] || { mkradmin propose --help; exit 1; }

target=$(seth --to-address "${1?which target address?}")
calldata=$(seth calldata ${2+"${@:2}"})

cat >&2 <<.
Proposing multisig action...
  target     $target
  value      ${MKRADMIN_VALUE-0}
  calldata   $calldata
.

sig="propose(address,bytes,uint256)(uint)"
value=${MKRADMIN_VALUE-0}
n=$(seth send @mkr_ms "$sig" "${target#0x}" "${calldata#0x}" "$value")
n=$(seth --to-dec "$n")

[[ $n -gt 0 ]] || fail "error: failed to create proposal"

echo "Successfully proposed action $n."
