#!/usr/bin/env bash
set -e
### mkradmin-confirm -- confirm proposed multisig action
### Usage: mkradmin confirm <action>
: ${1?missing action identifier}
mkradmin --ensure-account "${0##*/}"
echo >&2 "Confirming action $1..."
seth send @maker_multisig "confirm(uint)" "$1"
